name: Build

on:
  # mainへのPRマージをトリガーとしてワークフローを開始する
  pull_request:
    branches:
      - main
    types: [closed]

  # 手動実行デバッグ用
  workflow_dispatch: {}

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Demo/Assets/**', 'Demo/Packages/**', 'Demo/ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 2022.3.44f1
